import 'dart:math' show Random;

/// Web "device" identifier — a random v4 UUID minted by the CLIENT.
///
/// ## This is NOT equivalent to the native device id. Do not treat it as one.
///
/// The native path returns an identifier issued by the operating system
/// (`identifierForVendor` / Android id). This one is generated by the app
/// itself and persisted through `shared_preferences`, which on web is backed by
/// `localStorage`. That difference is not cosmetic — it changes what the value
/// can be used to prove:
///
///  - **Clearable.** Clearing site data, or the browser doing it under storage
///    pressure, destroys it. The next call mints a brand new id, so one student
///    on one machine can produce unlimited distinct "devices" by design of the
///    platform, not by circumventing anything.
///  - **Per-browser, not per-machine.** Chrome and Firefox on the same laptop
///    get different ids. A private/incognito window gets a different id again
///    and discards it on close.
///  - **Spoofable.** `localStorage` is readable and writable from the page's
///    own JS console. A student can copy another student's id in, or set their
///    own to any value, with no tooling and no exploit.
///
/// So: this id is usable as a weak, best-effort correlation signal — "probably
/// the same browser as last time" — and as an audit breadcrumb. It is NOT
/// evidence of a distinct physical device and must never be described as
/// binding a student to one. Device binding is not enforced anywhere in the
/// current system (see README §device binding), and this implementation is not
/// a reason to start: enforcing on a value the user can set themselves would
/// add the appearance of a control without the substance of one.
Future<String> platformDeviceId() async => _randomUuidV4();

/// Whether [platformDeviceId] is issued by the operating system (true) or
/// self-minted by the client (false). False here — see the doc comment above.
const bool deviceIdIsOsIssued = false;

/// RFC 4122 v4 UUID from a cryptographically secure source.
///
/// `Random.secure()` maps to `crypto.getRandomValues` on web. The randomness
/// quality is not the weak link here — the storage is (see above) — but there
/// is no reason to make it worse by using a seeded PRNG.
String _randomUuidV4() {
  final rng = Random.secure();
  final bytes = List<int>.generate(16, (_) => rng.nextInt(256));

  // Version 4 (random) and RFC 4122 variant bits.
  bytes[6] = (bytes[6] & 0x0f) | 0x40;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;

  String hex(int start, int end) => bytes
      .sublist(start, end)
      .map((b) => b.toRadixString(16).padLeft(2, '0'))
      .join();

  return '${hex(0, 4)}-${hex(4, 6)}-${hex(6, 8)}-${hex(8, 10)}-${hex(10, 16)}';
}
